on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Topic to search OpenAlex for"
        required: true
        default: "LLM red teaming"
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: "2022-01-01"
      max_pages:
        description: "Max pages to fetch"
        required: false
        default: "5"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run OpenAlex topic fetch
        run: |
          python openalex_topic_history.py \
            --topic "${{ github.event.inputs.topic }}" \
            --start-date "${{ github.event.inputs.start_date }}" \
            --max-pages "${{ github.event.inputs.max_pages }}"