name: Fetch Papers from OpenAlex

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Topic to search OpenAlex for"
        required: true
        default: "LLM red teaming"
      start_date:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: "2022-01-01"
      max_pages:
        description: "Max pages to fetch"
        required: false
        default: "100"
      gpt_model:
        description: "GPT model to use"
        required: false
        default: "gpt-4.1"
      gpt_temperature:
        description: "GPT temperature (0.0 to 1.0)"
        required: false
        default: "0.1"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}
      BASEROW_API_TOKEN: ${{ secrets.BASEROW_API_TOKEN }}
      BASEROW_TABLE_ID: ${{ secrets.BASEROW_TABLE_ID }}
      GPT_MODEL: ${{ github.event.inputs.gpt_model }}
      GPT_TEMPERATURE: ${{ github.event.inputs.gpt_temperature }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OpenAlex topic fetch
        run: |
          python search_papers.py \
            --topic "${{ github.event.inputs.topic }}" \
            --start-date "${{ github.event.inputs.start_date }}" \
            --max-pages "${{ github.event.inputs.max_pages }}"
