name: Test GitHub PAT Push (Fixed)

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository (disable default credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Create test file
        run: echo "<test>Git auth check</test>" > auth_test.xml

      - name: Configure Git and commit
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add auth_test.xml
          git commit -m "Test auth with PAT" || echo "Nothing to commit"

      - name: Show Git remotes
        run: git remote -v

      - name: Push test file
        run: |
          git push origin HEAD:main || (echo 'Retrying in 10s...' && sleep 10 && git push origin HEAD:main)