name: Update RSS Feed

on:
  schedule:
    - cron: "0 23 * * *"  # Runs every day at 1 AM UTC
  workflow_dispatch:     # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python paper_digest.py

    - name: Commit and push RSS file
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "AI Security Paper Digest Bot"
        git config --global user.email "bot@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add rss.xml
        git commit -m "Auto-update RSS feed"
        git push || (echo 'Retrying in 10s...' && sleep 10 && git push)