name: Update RSS Feed

on:
  schedule:
    - cron: "0 23 * * *"  # 7AM Singapore Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo with PAT
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate.py

    - name: Commit and push RSS file
      run: |
        git config --global user.name "AI Security Paper Digest Bot"
        git config --global user.email "bot@users.noreply.github.com"
        git add rss.xml
        git commit -m "Auto-update RSS feed at $(date -u)" || echo "No changes to commit"
        git push