name: Update RSS Feed

on:
  schedule:
    - cron: "0 23 * * *"  # Runs every day at 1 AM UTC
  workflow_dispatch:     # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python paper_digest.py

    - name: Commit and push RSS file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add rss.xml
        git commit -m "Update RSS feed on $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
        git push