name: Daily RSS Feed Update

on:
  schedule:
    - cron: "0 22 * * *" # Runs at 6AM SGT (22:00 UTC)
  workflow_dispatch:

jobs:
  run-daily-digest:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}
      QDRANT_API_URL: ${{ secrets.QDRANT_API_URL }}
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}
      AI_MODEL: ${{ secrets.AI_MODEL || 'moonshotai/kimi-dev-72b:free' }}
      TEMPERATURE: ${{ secrets.TEMPERATURE || '0.1' }}

    steps:
      - name: Checkout repo without default credentials
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check OpenRouter API key
        run: |
          if [ -z "$OPENROUTER_API_KEY" ]; then
            echo "::error::OPENROUTER_API_KEY is not set. Please set it in repository secrets."
            exit 1
          fi
          # Test the API key
          response=$(curl -s -H "Authorization: Bearer $OPENROUTER_API_KEY" https://openrouter.ai/api/v1/models)
          if echo "$response" | grep -q "error"; then
            echo "::error::OpenRouter API key is not valid. Please check your API key."
            exit 1
          fi

      - name: Check Qdrant credentials
        run: |
          if [ -z "$QDRANT_API_URL" ] || [ -z "$QDRANT_API_KEY" ]; then
            echo "::error::QDRANT_API_URL and QDRANT_API_KEY must be set in repository secrets."
            exit 1
          fi

      - name: Run daily digest script
        run: python update_rss.py

      - name: Git commit and push RSS file
        run: |
          git config --global user.name "AI Security Paper Digest Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add rss.xml
          git commit -m "Auto-update RSS feed" || echo "No changes to commit"
          git push origin HEAD:main || (echo 'Retrying in 10s...' && sleep 10 && git push origin HEAD:main)
