name: Daily RSS Feed Update

on:
  schedule:
    - cron: '0 22 * * *'  # Runs at 6AM SGT (22:00 UTC)
  workflow_dispatch:

jobs:
  run-daily-digest:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENALEX_EMAIL: ${{ secrets.OPENALEX_EMAIL }}
      BASEROW_API_TOKEN: ${{ secrets.BASEROW_API_TOKEN }}
      BASEROW_TABLE_ID: ${{ secrets.BASEROW_TABLE_ID }}
      RSS_FEED_URL: ${{ secrets.RSS_FEED_URL }}

    steps:
      - name: Checkout repo without default credentials
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily digest script
        run: python update_rss.py

      - name: Git commit and push RSS file
        run: |
          git config --global user.name "AI Security Paper Digest Bot"
          git config --global user.email "bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add rss.xml
          git commit -m "Auto-update RSS feed" || echo "No changes to commit"
          git push origin HEAD:main || (echo 'Retrying in 10s...' && sleep 10 && git push origin HEAD:main)